### ISSUE TITLE
11.0 Error on login

### ISSUE THREAD

**Issue by Tequima** [Todoloo-WoW/Todoloo#47]
**Version**  
1.3.1 May 2024

**Describe the bug**  
With pre-patch launch (11.0) getting an error on login and can no longer delete or add tasks to the list. See Bugsack report below.

**To Reproduce**  

**Screenshots**  

Message: ...e/AddOns/Todoloo/Source/Display/Utils/ScrollUtil.lua:296: attempt to call method 'SetNotifyDragSource' (a nil value)

Time: Sat Jul 27 07:36:52 2024

Count: 1

Stack: ...e/AddOns/Todoloo/Source/Display/Utils/ScrollUtil.lua:296: attempt to call method 'SetNotifyDragSource' (a nil value)

[string "=[C]"]: in function `SetNotifyDragSource'

[string "@Interface/AddOns/Todoloo/Source/Display/Utils/ScrollUtil.lua"]:296: in function <...e/AddOns/Todoloo/Source/Display/Utils/ScrollUtil.lua:295>

[string "@Interface/AddOns/Todoloo/Source/Display/Utils/ScrollUtil.lua"]:330: in function `InitDefaultTaskListDragBehavior'

[string "@Interface/AddOns/Todoloo/Source/Display/TaskManager/TaskList.lua"]:134: in function <...dOns/Todoloo/Source/Display/TaskManager/TaskList.lua:133>

[string "@Interface/AddOns/Todoloo/Source/Display/TaskManager/TaskList.lua"]:145: in function <...dOns/Todoloo/Source/Display/TaskManager/TaskList.lua:138>

**Comment by detilium** [comment]
Hello Tequima.

I'm aware that Todoloo has issues with the current version. I'm currently working on a new version, and expect to have a working version available within the next 78 days.

**Comment by detilium** [comment]
Hello Tequima,

I've just released a new version that should support v11.0.0. It'll be available on CurseForge in a few minutes.

If you're experiencing any issues with the new release, don't hesitate to get back to me :)
