### ISSUE TITLE
Weekly task will renew daily

### ISSUE THREAD

**Issue by mhx3** [Todoloo-WoW/Todoloo#51]
**Version**  
_What version of Todoloo do you have installed?._
v11.0.2

**Describe the bug**  
_A clear and concise description of what the bug is._
I set some tasks under a weekly group, but the tasks will auto renew with daily group.
I use Chinese and not sure if local time affects.
I copy the tasks from one character to another, in the todoloo.lua. not sure if it makes it happen. Because for some characters, they need to do the same weekly tasks you know.

**To Reproduce**  
_Include the steps to reproduce the behavior._
I meet this problem at the 2nd day using this addon, and I re-check all the finished tasks. Now they are all un-checked now at the 3rd day. I think they are wrongly auto un-checked, because weekly tasks should renew on Thursday.

**Screenshots**  
_If applicable, add screenshots to help explain your problem._

**Comment by mhx3** [comment]
I read the ResetManager.lua, and found the following:

local function ShouldResetGroup(group, previousDailyReset, previousWeeklyReset)
    local lastResetPerformed = Todoloo.Config.Get(Todoloo.Config.Options.LAST_RESET_PERFORMED)
    if group.reset == TODOLOO_RESET_INTERVALS.Daily and lastResetPerformed < previousDailyReset then
        -- reset daily groups
        return true
    **elseif group.reset == TODOLOO_RESET_INTERVALS.Weekly and lastResetPerformed < previousDailyReset then**
        -- reset weekly groups
        return true
    end
I guess the bold part should be **< previousWeeklyReset then**

**Comment by detilium** [comment]
Hi @mhx3

Well spotted. I've fixed the bug and am working on a release right now. And update sohuld be available within 10-15 minutes.

Thank you for your bug report and your debugging ;)
