### ISSUE TITLE
Taint to object tracker.

### ISSUE THREAD

**Issue by Gateswong** [Todoloo-WoW/Todoloo#52]
**Version**  
11.0.2.1

**Describe the bug**  
This addon taints the object tracker, prevent quest item to be used.

**To Reproduce**  
I got this issue while doing "Enchanted Shrubbery" (Enchant weekly in emerald dream, 10.2), I'm trying to use the quest item button from the quest tracker.

![image](https://github.com/user-attachments/assets/d3d130d0-abb2-4103-8540-218200ed5e91)

**Taint Log**  
9/9 01:06:07.713  Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:94
9/9 01:06:07.713  An action was blocked because of taint from Todoloo - UseQuestLogSpecialItem()
9/9 01:06:07.713      Interface/AddOns/Blizzard_ObjectiveTracker/Blizzard_ObjectiveTrackerShared.lua:94

**Comment by detilium** [comment]
Hey @Gateswong 

I'm aware of the issue but unfortunately I haven't been able to isolate the problem yet, for me to fix the issue. It's an ongoing process, and I'm still looking for the problem.

I apologize for the inconvenience, but I can assure you I'm looking into it.

**Comment by detilium** [comment]
Hello,

This issue seems to be resolved with version 11.0.7 of World of Warcraft and the latest version (v11.0.7.0) of Todoloo.

I'm closing the issue but you're welcome to reopen if your still experiencing problem with taint.
