### ISSUE TITLE
Allow global access to the `Todoloo` table/API

### ISSUE THREAD

**Issue by filliph** [Todoloo-WoW/Todoloo#55]
**Is your feature request related to a problem? Please describe.**  
It is currently impossible for other add-ons that overwrite the default Objective Tracker to add compatibility with the embedded Todoloo tracker because the table `Todoloo` is private.

**Describe the solution you'd like**  
Assign a global variable that exposes the `Todoloo` table such that other addons can replicate the tracker functionality in their own objective tracker.

**Describe alternatives you've considered**  
Using the standalone tracker is sub-optimal as our screens are already quite cluttered 😅 

**Additional context**  
This is specifically related to GW2_UI, which already has added support for PetTracker due to a similar feature request.

**Comment by detilium** [comment]
Hey bud.

I've made the Todoloo table globally available in the next release for other addons to use.

**Comment by detilium** [comment]
The new version has been released and the addon table is now fully available :)
